#!/usr/bin/make -f

image=registry
tag=SNAPSHOT
name=$(image)-$(tag)
registry=crashvb

runargs=--env=REGISTRY_GENERATE_PASSWORD=true \
	--env=REGISTRY_HTTP_SECRET=dummy \
	--env=REGISTRY_HTTP_TLS_CERTIFICATE=/etc/ssl/certs/docker.crt \
	--env=REGISTRY_HTTP_TLS_KEY=/etc/ssl/private/docker.key \
	--publish=5000:5000/tcp \
	--volume=/etc/ssl/certs/docker.crt:/etc/ssl/certs/docker.crt:ro \
	--volume=/etc/ssl/private/docker.key:/etc/ssl/private/docker.key:ro
